# Generated by Django 5.1.3 on 2024-11-30 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_room_message_user_message_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
